name: Test CI

on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get the user who triggered the workflow
        id: get-user
        uses: actions/github-script@v6
        with:
          script: |
            const user = process.env.GITHUB_ACTOR;
            const response = await fetch(`https://api.github.com/users/${user}`);
            const data = await response.json();
            return {
              username: data.login,
              avatar_url: data.avatar_url,
              profile_url: data.html_url
            };
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}

      - name: Set version number
        id: version
        run: echo "VERSION=5.0.2" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "v${{ env.VERSION }}"
          body: |
            Release created by ${{ steps.get-user.outputs.avatar_url }} - ${{ steps.get-user.outputs.username }}-{{ steps.get-user.outputs.profile_url }} devops lead!
          draft: false
          prerelease: false
