name: Check Time and Conditionally Run CD

on:
  push:
    branches:
      - main

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Set up time and date
        id: date
        run: echo "current_time=$(TZ=Asia/Kolkata date +'%H:%M')" >> $GITHUB_ENV

      - name: Check if current time is within specified ranges
        id: time-check
        run: |
          if [[ "$current_time" > "08:00" && "$current_time" < "13:15" ]] || [[ "$current_time" > "13:30" && "$current_time" < "18:00" ]]; then
            echo "Time is within the allowed range. Continuing the workflow."
          else
            echo "Time is not within the allowed range. Exiting the workflow."
            exit 1
          fi