name: Check Time and Conditionally Run CD

on:
  push:
    branches:
      - main

jobs:
  check-time:
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.time-check.outputs.continue }}
    steps:
      - name: Set up time and date
        id: date
        run: |
          echo "current_time=$(TZ=Asia/Kolkata date +'%H:%M')" >> $GITHUB_ENV
          echo "current_day=$(TZ=Asia/Kolkata date +'%u')" >> $GITHUB_ENV

      - name: Log current time and day
        run: |
          echo "Current time in IST is ${{ env.current_time }}"
          echo "Current day in IST is ${{ env.current_day }}"

      - name: Check if current time is within specified ranges or weekend
        id: time-check
        run: |
          echo "Checking if current time (${{ env.current_time }}) is within allowed ranges..."
          if [[ "${{ env.current_day }}" -eq 4 ]] || [[ "${{ env.current_day }}" -eq 7 ]]; then
            echo "Today is Saturday or Sunday. Continuing the workflow."
            echo "::set-output name=continue::true"
          elif [[ "${{ env.current_time }}" > "11:00" && "${{ env.current_time }}" < "13:15" ]] || [[ "${{ env.current_time }}" > "13:30" && "${{ env.current_time }}" < "18:00" ]]; then
            echo "Time is within the disallowed range. Exiting the workflow."
            echo "::set-output name=continue::false"
            exit 0
          else
            echo "Time is outside the disallowed range. Continuing the workflow."
            echo "::set-output name=continue::true"
