name: Check Time and Conditionally Run CD

on:
  workflow_call:
    outputs:
      continue:
        description: 'Whether to continue the workflow'
        value: ${{ jobs.check-time.outputs.continue }}

jobs:
  check-time:
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.time-check.outputs.continue }}
    steps:
      - name: Set up time and date
        id: date
        run: echo "current_time=$(TZ=Asia/Kolkata date +'%H:%M')" >> $GITHUB_ENV

      - name: Log current time
        run: echo "Current time in IST is ${{ env.current_time }}"

      - name: Check if current time is within specified ranges
        id: time-check
        run: |
          echo "Checking if current time (${{ env.current_time }}) is within allowed ranges..."

          current_time=$(date -d "${{ env.current_time }}" +%s)
          six_pm=$(date -d "18:00" +%s)
          nine_am=$(date -d "09:00" +%s)
          one_fifteen_pm=$(date -d "13:15" +%s)
          one_thirty_pm=$(date -d "13:30" +%s)

          if [[ $current_time -ge $six_pm ]] || [[ $current_time -le $nine_am ]] || \
             ([[ $current_time -ge $one_fifteen_pm ]] && [[ $current_time -le $one_thirty_pm ]]); then
            echo "Time is within the allowed range. Continuing the workflow."
            echo "::set-output name=continue::true"
          else
            echo "Time is outside the allowed range. Exiting the workflow."
            echo "::set-output name=continue::false"
            exit 0
          fi