name: Check Time and Conditionally Run CD

on:
  push:
    branches:
      - main

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Set up time and date
        id: date
        run: echo "current_time=$(TZ=Asia/Kolkata date +'%H:%M')" >> $GITHUB_ENV

      - name: Log current time
        run: echo "Current time in IST is ${{ env.current_time }}"

      - name: Check if current time is within specified ranges
        id: time-check
        run: |
          echo "Checking if current time (${{ env.current_time }}) is within allowed ranges..."
          if [[ "${{ env.current_time }}" > "08:00" && "${{ env.current_time }}" < "13:15" ]] || [[ "${{ env.current_time }}" > "13:30" && "${{ env.current_time }}" < "18:00" ]]; then
            echo "Time is within the disallowed range. Exiting the workflow."
            exit 1
          else
            echo "Time is outside the disallowed range. Continuing the workflow."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-time
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your CD steps here
      - name: Deploy
        run: echo "Deploying..."
