name: Test CI

on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET }}
    steps:
      - name: Set version number
        id: version
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          release_name: "v${{ env.VERSION }}"
