# .github/workflows/pr-template-check.yml

name: PR Template Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Target Branch
        if: github.event.pull_request.base.ref == 'main'
        run: |
          echo "PR is targeting the main branch."
          PR_TEMPLATE=$(cat .github/PULL_REQUEST_TEMPLATE/main_pr_template.md)
          echo "Template Content:"
          echo "$PR_TEMPLATE"
          PR_BODY=$(jq -Rsa '.' <<< "$PR_TEMPLATE")
          echo "Formatted PR Body:"
          echo "$PR_BODY"
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -X PATCH \
               -d "{\"body\":$PR_BODY}" \
               "${{ github.event.pull_request.url }}"

      - name: Skip Template Check for Other Branches
        if: github.event.pull_request.base.ref != 'main'
        run: echo "PR is not targeting the main branch. Skipping template application."
